const txs=[["🍴","Swiggy","Food & Dining","−₹450","orange"],["▣","Uber","Transport","−₹320","blue"],["₹","Salary from ABC Corp","Income","+₹80,000","green","income"],["a","Amazon","Shopping","−₹1,299","yellow"]];
const txRows=(large=false)=>txs.map(x=>`<article class="tx"><span class="tx-icon ${x[4]}">${x[0]}</span><p><b>${x[1]}</b><small>${x[2]}</small></p><strong class="${x[5]||""}">${x[3]}</strong></article>`).join("");
const views={
home:`<header class="header"><div><small>Good Morning,</small><h2>Vicky 👋</h2></div><div class="avatar">V</div></header><section class="balance"><small>Total Balance</small><strong>₹1,25,430.50</strong><span class="trend">▲ 12.5% <i>vs last month</i></span><div class="split"><p><small>Income</small><b>₹1,80,000</b></p><p><small>Expense</small><b>₹54,569</b></p></div></section><section class="section"><div class="section-head"><h3>Quick Overview</h3><button class="text-button">This Month⌄</button></div><div class="chart-row"><div class="donut"><div><small>Total Expense</small><b>₹54,569</b></div></div><ul class="legend"><li><i class="c1"></i><span>Housing</span><b>₹18,000</b></li><li><i class="c2"></i><span>Food & Dining</span><b>₹9,850</b></li><li><i class="c3"></i><span>Transport</span><b>₹6,300</b></li><li><i class="c4"></i><span>Shopping</span><b>₹4,750</b></li><li><i class="c5"></i><span>Others</span><b>₹15,669</b></li></ul></div></section><section class="section recent card"><div class="section-head"><h3>Recent Transactions</h3><button class="text-button" onclick="showView('transactions')">View All</button></div>${txRows() }</section>`,
transactions:`<div class="title-row"><div><h2>Transactions</h2><p>August 2026</p></div><button class="pill-button">Filter</button></div><div class="summary"><div class="card"><small>Income</small><strong class="income">₹1,80,000</strong></div><div class="card"><small>Expenses</small><strong>₹54,569</strong></div></div><div class="filterbar"><button class="filter active">All</button><button class="filter">Income</button><button class="filter">Expenses</button></div><section class="card transaction-list">${txRows(true)}${txRows(true)}</section>`,
budgets:`<div class="title-row"><div><h2>Budgets</h2><p>Plan your monthly spending</p></div><button class="pill-button">+ Add</button></div><section class="card hero-budget"><small>Monthly spending</small><div><strong>₹54,569</strong> <small>of ₹75,000</small></div><div class="progress"><span style="width:73%"></span></div></section><div class="section-head"><h3>Your budgets</h3><button class="text-button">August⌄</button></div><section class="budget-list section"><div class="card budget-item"><div><b>Food & Dining</b><small>₹9,850 / ₹14,000</small></div><div class="progress"><span style="width:70%"></span></div></div><div class="card budget-item"><div><b>Housing</b><small>₹18,000 / ₹20,000</small></div><div class="progress"><span style="width:90%;background:#ffb92e"></span></div></div><div class="card budget-item"><div><b>Transport</b><small>₹6,300 / ₹10,000</small></div><div class="progress"><span style="width:63%;background:#3f8cff"></span></div></div><div class="card budget-item"><div><b>Shopping</b><small>₹4,750 / ₹8,000</small></div><div class="progress"><span style="width:59%;background:#ff5b6e"></span></div></div></section>`,
profile:`<div class="title-row"><div><h2>Profile</h2><p>Account and preferences</p></div></div><section class="profile-head"><div class="avatar">V</div><div><h3>Vicky Sharma</h3><p>vicky@example.com</p><span class="plan">FINTRACK PLUS</span></div></section><h3 style="font-size:13px">Account</h3><section class="settings section"><div class="setting card"><span>Personal information</span><span>›</span></div><div class="setting card"><span>Linked accounts</span><span>›</span></div><div class="setting card"><span>Categories</span><span>›</span></div><div class="setting card"><span>Notifications</span><span>›</span></div><div class="setting card"><span>Privacy & security</span><span>›</span></div><div class="setting card"><span>Appearance</span><span>Dark ›</span></div></section>`
};
const view=document.querySelector("#view");
function showView(name){view.innerHTML=views[name];view.scrollTop=0;document.querySelectorAll("nav [data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===name))}
window.showView=showView;
document.querySelectorAll("nav [data-view]").forEach(b=>b.onclick=()=>showView(b.dataset.view));
const modal=document.querySelector("#modal");document.querySelector("#add").onclick=()=>modal.classList.add("open");document.querySelector("#close").onclick=()=>modal.classList.remove("open");
document.querySelector("#save").onclick=()=>{modal.classList.remove("open");const t=document.querySelector("#toast");t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)};
showView("home");